/** 莊股（EQ-D7）繁中文案 — UX v1.1 */
export const EQUITY_COPY = {
  tab: "莊股",
  title: "莊股行情",
  subtitle: "供需浮動 · 持倉投機（非真實證券）",
  price: "現價",
  change: "漲跌",
  holdings: (n: number) => `持倉 ${n}`,
  buyCta: "買入",
  sellCta: "賣出",
  previewBuy: (n: number) => `預估支付 🪙${n}（含手續費）`,
  previewSell: (n: number) => `預估實收 🪙${n}（已扣手續費）`,
  needGold: "金幣不足",
  needShares: "無持倉",
  cap: "已達持倉上限",
  qtyCap: "超過單筆上限",
  feeHigh: "手續費過高，無法賣出",
  empty: "尚未持有莊股。買入後可在此賣出。",
  successBuy: (name: string, q: number, gold: number) => `已買入 ${name}×${q}，－🪙${gold}`,
  successSell: (name: string, q: number, gold: number) => `已賣出 ${name}×${q}，＋🪙${gold}`,
  hint: "莊股價格隨買賣浮動；農產仍請到「賣出／買入」換固定價。",
  disclaimer: "遊戲內虛構標的，非真實投資。",
  invalidQuantity: "數量無效",
  loading: "載入莊股行情…",
  genericError: "莊股交易失敗，請稍後再試。",
} as const;
