/** 零售 tab 文案（ux-spec-retail §6.2；FE-RICH-3 銅錠語意）。 */
export const RETAIL_COPY = {
  tab: "零售",
  title: "莊頭零售",
  subtitle: "貨架自動售賣 · 接客單賣麵包",
  hint: "本頁一屏睇清貨架標價與客單出價；批發固定價請用「賣出」tab，結算皆以銅錠計。",
  ordersSectionTitle: "客單",
  haulNote: "本地零售免運。",
  loading: "載入客單…",
  offerQty: (n: number) => `要 ${n} 個`,
  bid: (n: number) => `出價 🟠${n} 銅錠／個`,
  preview: (n: number) => `預估實收 🟠${n} 銅錠`,
  accept: "接單",
  needStock: "麵包不足",
  needGold: "銅錠不足",
  expired: "客單已失效",
  emptyOffers: "客流稀少，稍後再來。",
  emptySlot: (slot: number) => `槽位 ${slot} · 等待客流`,
  emptyStock: "尚未有麵包。做出麵包再開舖接客。",
  success: (qty: number, gold: number) => `已售出麵包×${qty}，＋🟠${gold} 銅錠`,
  genericError: "零售操作失敗，請稍後再試。",
  stockBanner: (qty: number) => `麵包庫存 ${qty}`,
} as const;
