import { RELEASED_IN_VERSION } from "./config";
import {
  ITEM_CURRENCY_TYPE_ID,
  ITEM_COPPER_INGOT_ID,
  ITEM_GOLD_ID,
  STARTING_COPPER,
} from "./market-config";
import type { BuildingDef, ItemDef, ItemPropertyDef, ItemTypeDef, ProductionRuleDef } from "./types";

/** GDD 範例屬性（純度、含水）；農業 MVP 最小集合，其餘（熱值、同位素）留待後續切片。 */
export const itemProperties: ItemPropertyDef[] = [
  {
    id: "iprop_moisture",
    code: "moisture",
    name: "含水",
    value_kind: "number",
    is_active: true,
    released_in_version: RELEASED_IN_VERSION,
  },
  {
    id: "iprop_purity",
    code: "purity",
    name: "純度",
    value_kind: "number",
    is_active: true,
    released_in_version: RELEASED_IN_VERSION,
  },
];

/** TODO(product) 待確認：汲水工時（遊戲秒，佔位 ≈10 現實秒 @ timeScale=60） */
export const PLACEHOLDER_DRAW_WATER_DURATION_GAME_SEC = 600;
/** TODO(product) 待確認：每次汲水產出水數量；無輸入消耗 */
export const PLACEHOLDER_DRAW_WATER_OUTPUT_QTY = 5;
/** TODO(product) 待確認：留種工時（遊戲秒） */
export const PLACEHOLDER_SAVE_SEED_DURATION_GAME_SEC = 1800;
/** TODO(product) 待確認：留種輸入小麥數量 */
export const PLACEHOLDER_SAVE_SEED_WHEAT_INPUT_QTY = 2;
/** TODO(product) 待確認：留種產出種子數量 */
export const PLACEHOLDER_SAVE_SEED_OUTPUT_QTY = 1;

export const itemTypes: ItemTypeDef[] = [
  { id: "it_crop", code: "crop", name: "作物", is_active: true, released_in_version: RELEASED_IN_VERSION },
  { id: "it_produce", code: "produce", name: "農產加工", is_active: true, released_in_version: RELEASED_IN_VERSION },
  { id: "it_commodity", code: "commodity", name: "大宗現貨", is_active: true, released_in_version: RELEASED_IN_VERSION },
  { id: "it_industrial", code: "industrial", name: "工業品", is_active: true, released_in_version: RELEASED_IN_VERSION },
  // TODO(product): 貨幣是否獨立 Player.gold 欄未定；現用 inventory 物品佔位。
  { id: ITEM_CURRENCY_TYPE_ID, code: "currency", name: "貨幣", is_active: true, released_in_version: RELEASED_IN_VERSION },
];

export const items: ItemDef[] = [
  { id: "item_seed_wheat", code: "seed_wheat", type_id: "it_crop", layer: "T", derived_tier: 1, is_active: true, released_in_version: RELEASED_IN_VERSION },
  { id: "item_wheat", code: "wheat", type_id: "it_crop", layer: "T", derived_tier: 1, is_active: true, released_in_version: RELEASED_IN_VERSION },
  { id: "item_straw", code: "straw", type_id: "it_crop", layer: "T", derived_tier: 1, is_active: true, released_in_version: RELEASED_IN_VERSION },
  { id: "item_water", code: "water", type_id: "it_crop", layer: "T", derived_tier: 1, is_active: true, released_in_version: RELEASED_IN_VERSION },
  { id: "item_flour", code: "flour", type_id: "it_produce", layer: "P", derived_tier: 1, is_active: true, released_in_version: RELEASED_IN_VERSION },
  { id: "item_feed", code: "feed", type_id: "it_produce", layer: "P", derived_tier: 1, is_active: true, released_in_version: RELEASED_IN_VERSION },
  { id: "item_dough", code: "dough", type_id: "it_produce", layer: "P", derived_tier: 1, is_active: true, released_in_version: RELEASED_IN_VERSION },
  { id: "item_bread", code: "bread", type_id: "it_produce", layer: "P", derived_tier: 2, is_active: true, released_in_version: RELEASED_IN_VERSION },
  { id: "item_egg", code: "egg", type_id: "it_produce", layer: "P", derived_tier: 1, is_active: true, released_in_version: RELEASED_IN_VERSION },
  { id: "item_milk", code: "milk", type_id: "it_produce", layer: "P", derived_tier: 1, is_active: true, released_in_version: RELEASED_IN_VERSION },
  { id: "item_cake", code: "cake", type_id: "it_produce", layer: "P", derived_tier: 2, is_active: true, released_in_version: RELEASED_IN_VERSION },
  { id: "item_seed_cotton", code: "seed_cotton", type_id: "it_crop", layer: "T", derived_tier: 1, is_active: true, released_in_version: RELEASED_IN_VERSION },
  { id: "item_cotton", code: "cotton", type_id: "it_crop", layer: "T", derived_tier: 1, is_active: true, released_in_version: RELEASED_IN_VERSION },
  { id: "item_cloth", code: "cloth", type_id: "it_industrial", layer: "P", derived_tier: 1, is_active: true, released_in_version: RELEASED_IN_VERSION },
  { id: "item_ore", code: "ore", type_id: "it_industrial", layer: "T", derived_tier: 1, is_active: true, released_in_version: RELEASED_IN_VERSION },
  { id: "item_iron", code: "iron", type_id: "it_industrial", layer: "P", derived_tier: 1, is_active: true, released_in_version: RELEASED_IN_VERSION },
  // TODO(product): 金幣顯示名／圖示；不進生產 DAG。
  {
    id: ITEM_GOLD_ID,
    code: "gold",
    type_id: ITEM_CURRENCY_TYPE_ID,
    layer: "C",
    derived_tier: 0,
    is_active: true,
    released_in_version: RELEASED_IN_VERSION,
  },
  {
    id: "item_oil",
    code: "oil",
    type_id: "it_commodity",
    layer: "C",
    derived_tier: 0,
    is_active: true,
    released_in_version: RELEASED_IN_VERSION,
  },
];

export const rules: ProductionRuleDef[] = [
  {
    id: "rule_grow_wheat",
    code: "grow_wheat",
    parent_rule_id: null,
    inputs: [
      { key: "seed", item_id: "item_seed_wheat", qty: 1 },
      { key: "water", item_id: "item_water", qty: 1 },
    ],
    outputs: [
      { item_id: "item_wheat", qty: 2 },
      { item_id: "item_straw", qty: 1 },
    ],
    duration_game_sec: 3600,
    formulas: {},
    compositions: [],
    overrides: {},
    is_active: true,
    released_in_version: RELEASED_IN_VERSION,
    optimizations: [{ code: "water_saving", input_factor: { water: 0.5 }, duration_factor: 1.5 }],
  },
  {
    id: "rule_mill_flour",
    code: "mill_flour",
    parent_rule_id: null,
    inputs: [{ item_id: "item_wheat", qty: 2 }],
    outputs: [{ item_id: "item_flour", qty: 1 }],
    duration_game_sec: 1800,
    formulas: {},
    compositions: [],
    overrides: {},
    is_active: true,
    released_in_version: RELEASED_IN_VERSION,
  },
  {
    id: "rule_mix_feed",
    code: "mix_feed",
    parent_rule_id: null,
    inputs: [
      { item_id: "item_straw", qty: 2 },
      { item_id: "item_wheat", qty: 1 },
    ],
    outputs: [{ item_id: "item_feed", qty: 2 }],
    duration_game_sec: 1200,
    formulas: {},
    compositions: [],
    overrides: {},
    is_active: true,
    released_in_version: RELEASED_IN_VERSION,
  },
  {
    id: "rule_make_dough",
    code: "make_dough",
    parent_rule_id: null,
    inputs: [
      { item_id: "item_flour", qty: 1 },
      { item_id: "item_water", qty: 1 },
    ],
    outputs: [{ item_id: "item_dough", qty: 1 }],
    duration_game_sec: 600,
    formulas: {},
    compositions: [],
    overrides: {},
    is_active: true,
    released_in_version: RELEASED_IN_VERSION,
  },
  {
    id: "rule_bake_bread",
    code: "bake_bread",
    parent_rule_id: null,
    inputs: [{ item_id: "item_dough", qty: 1 }],
    outputs: [{ item_id: "item_bread", qty: 1 }],
    duration_game_sec: 1200,
    formulas: {},
    compositions: [],
    overrides: {},
    is_active: true,
    released_in_version: RELEASED_IN_VERSION,
    optimizations: [{ code: "batch", output_factor: 2, input_factor: { item_dough: 2 } }],
  },
  {
    id: "rule_draw_water",
    code: "draw_water",
    parent_rule_id: null,
    inputs: [],
    outputs: [{ item_id: "item_water", qty: PLACEHOLDER_DRAW_WATER_OUTPUT_QTY }],
    duration_game_sec: PLACEHOLDER_DRAW_WATER_DURATION_GAME_SEC,
    formulas: {},
    compositions: [],
    overrides: {},
    is_active: true,
    released_in_version: RELEASED_IN_VERSION,
  },
  {
    id: "rule_raise_livestock",
    code: "raise_livestock",
    parent_rule_id: null,
    inputs: [
      { item_id: "item_feed", qty: 1 },
      { item_id: "item_water", qty: 1 },
    ],
    outputs: [
      { item_id: "item_egg", qty: 2 },
      { item_id: "item_milk", qty: 1 },
    ],
    duration_game_sec: 2400,
    formulas: {},
    compositions: [],
    overrides: {},
    is_active: true,
    released_in_version: RELEASED_IN_VERSION,
  },
  {
    id: "rule_bake_cake",
    code: "bake_cake",
    parent_rule_id: null,
    inputs: [
      { item_id: "item_flour", qty: 1 },
      { item_id: "item_egg", qty: 2 },
      { item_id: "item_milk", qty: 1 },
    ],
    outputs: [{ item_id: "item_cake", qty: 1 }],
    duration_game_sec: 1800,
    formulas: {},
    compositions: [],
    overrides: {},
    is_active: true,
    released_in_version: RELEASED_IN_VERSION,
  },
  {
    id: "rule_grow_cotton",
    code: "grow_cotton",
    parent_rule_id: null,
    inputs: [
      { key: "seed", item_id: "item_seed_cotton", qty: 1 },
      { key: "water", item_id: "item_water", qty: 1 },
    ],
    outputs: [{ item_id: "item_cotton", qty: 3 }],
    duration_game_sec: 3600,
    formulas: {},
    compositions: [],
    overrides: {},
    is_active: true,
    released_in_version: RELEASED_IN_VERSION,
  },
  {
    id: "rule_weave_cloth",
    code: "weave_cloth",
    parent_rule_id: null,
    inputs: [{ item_id: "item_cotton", qty: 3 }],
    outputs: [{ item_id: "item_cloth", qty: 1 }],
    duration_game_sec: 1800,
    formulas: {},
    compositions: [],
    overrides: {},
    is_active: true,
    released_in_version: RELEASED_IN_VERSION,
  },
  {
    id: "rule_mine_ore",
    code: "mine_ore",
    parent_rule_id: null,
    inputs: [{ item_id: "item_water", qty: 1 }],
    outputs: [{ item_id: "item_ore", qty: 2 }],
    duration_game_sec: 2400,
    formulas: {},
    compositions: [],
    overrides: {},
    is_active: true,
    released_in_version: RELEASED_IN_VERSION,
  },
  {
    id: "rule_smelt_iron",
    code: "smelt_iron",
    parent_rule_id: null,
    inputs: [
      { item_id: "item_ore", qty: 2 },
      { item_id: "item_oil", qty: 1 },
    ],
    outputs: [{ item_id: "item_iron", qty: 2 }],
    duration_game_sec: 2400,
    formulas: {},
    compositions: [],
    overrides: {},
    is_active: true,
    released_in_version: RELEASED_IN_VERSION,
  },
  {
    id: "rule_save_seed",
    code: "save_seed",
    parent_rule_id: null,
    inputs: [{ item_id: "item_wheat", qty: PLACEHOLDER_SAVE_SEED_WHEAT_INPUT_QTY }],
    outputs: [{ item_id: "item_seed_wheat", qty: PLACEHOLDER_SAVE_SEED_OUTPUT_QTY }],
    duration_game_sec: PLACEHOLDER_SAVE_SEED_DURATION_GAME_SEC,
    formulas: {},
    compositions: [],
    overrides: {},
    is_active: true,
    released_in_version: RELEASED_IN_VERSION,
  },
];

export const buildingDefs: BuildingDef[] = [
  {
    id: "bdef_field",
    code: "field",
    name: "田",
    system_code: "agriculture",
    allowed_rule_ids: ["rule_grow_wheat", "rule_grow_cotton", "rule_save_seed"],
    queue_limit: 1,
    is_active: true,
    released_in_version: RELEASED_IN_VERSION,
  },
  {
    id: "bdef_silo",
    code: "silo",
    name: "倉",
    system_code: "agriculture",
    allowed_rule_ids: [],
    queue_limit: 1,
    is_active: true,
    released_in_version: RELEASED_IN_VERSION,
  },
  {
    id: "bdef_mill",
    code: "mill",
    name: "磨坊",
    system_code: "agriculture",
    allowed_rule_ids: ["rule_mill_flour", "rule_mix_feed"],
    queue_limit: 1,
    is_active: true,
    released_in_version: RELEASED_IN_VERSION,
  },
  {
    id: "bdef_oven",
    code: "oven",
    name: "爐",
    system_code: "agriculture",
    allowed_rule_ids: ["rule_make_dough", "rule_bake_bread"],
    queue_limit: 1,
    is_active: true,
    released_in_version: RELEASED_IN_VERSION,
  },
  {
    id: "bdef_well",
    code: "well",
    name: "水井",
    system_code: "agriculture",
    allowed_rule_ids: ["rule_draw_water"],
    queue_limit: 1,
    is_active: true,
    released_in_version: RELEASED_IN_VERSION,
  },
  {
    id: "bdef_trading_post",
    code: "trading_post",
    name: "莊外商行",
    system_code: "agriculture",
    allowed_rule_ids: [],
    queue_limit: 1,
    is_active: true,
    released_in_version: RELEASED_IN_VERSION,
  },
  {
    id: "bdef_ranch",
    code: "ranch",
    name: "牧場",
    system_code: "agriculture",
    allowed_rule_ids: ["rule_raise_livestock"],
    queue_limit: 1,
    is_active: true,
    released_in_version: RELEASED_IN_VERSION,
  },
  {
    id: "bdef_food_factory",
    code: "food_factory",
    name: "食品廠",
    system_code: "industry",
    allowed_rule_ids: ["rule_bake_cake"],
    queue_limit: 1,
    is_active: true,
    released_in_version: RELEASED_IN_VERSION,
  },
  {
    id: "bdef_textile_mill",
    code: "textile_mill",
    name: "紡織廠",
    system_code: "industry",
    allowed_rule_ids: ["rule_weave_cloth"],
    queue_limit: 1,
    is_active: true,
    released_in_version: RELEASED_IN_VERSION,
  },
  {
    id: "bdef_mine",
    code: "mine",
    name: "礦場",
    system_code: "mining",
    allowed_rule_ids: ["rule_mine_ore"],
    queue_limit: 1,
    is_active: true,
    released_in_version: RELEASED_IN_VERSION,
  },
  {
    id: "bdef_smelter",
    code: "smelter",
    name: "冶煉廠",
    system_code: "mining",
    allowed_rule_ids: ["rule_smelt_iron"],
    queue_limit: 1,
    is_active: true,
    released_in_version: RELEASED_IN_VERSION,
  },
];

/** 開局預放建築（倉 `bdef_silo` 不預放；D3 未定；**已拍板 D2** 含水井）。 */
export const seedPlacedBuildingDefIds = [
  "bdef_field",
  "bdef_mill",
  "bdef_oven",
  "bdef_well",
  "bdef_trading_post",
] as const;

export const startingInventory: Record<string, number> = {
  item_seed_wheat: 40,
  item_wheat: 0,
  item_straw: 0,
  item_water: 80,
  item_flour: 0,
  item_feed: 0,
  item_dough: 0,
  item_bread: 0,
  [ITEM_COPPER_INGOT_ID]: STARTING_COPPER,
};

export const METHOD_NAME: Record<string, string> = {
  method_grow_wheat_default: "種植小麥",
  method_grow_wheat_water_saving: "省水種植",
  method_mill_flour_default: "磨粉",
  method_mix_feed_default: "拌飼料",
  method_make_dough_default: "和麵",
  method_bake_bread_default: "烘烤麵包",
  method_bake_bread_batch: "批量烘烤",
  method_draw_water_default: "汲水",
  method_save_seed_default: "留種",
  method_raise_livestock_default: "飼養禽畜",
  method_bake_cake_default: "焗蛋糕",
  method_grow_cotton_default: "種棉花",
  method_weave_cloth_default: "紡紗織布",
  method_mine_ore_default: "採礦",
  method_smelt_iron_default: "煉鐵",
};
